djangosite/djangosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path("recipe/", include("recipe_site.urls"))
]

djangosite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

djangosite/recipe_site/urls.py
from django.urls import path

from recipe_site.views.home import HomeView
from recipe_site.views.recipes_index import RecipeIndexView
from recipe_site.views.user_login import UserLoginView
from recipe_site.views.user_logout import UserLogoutView
from recipe_site.views.user_registration import UserRegistrationView

app_name = 'recipe_site'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path("home/", HomeView.as_view(), name="home"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("recipes/", RecipeIndexView.as_view(), name="recipes"),
]

djangosite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

djangosite/polls/models/choice.py
from django.db import models

from polls.models.question import Question


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

djangosite/polls/models/question.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        yesterday = now - datetime.timedelta(days=1)
        return yesterday <= self.pub_date <= now

    def __str__(self):
        return self.question_text

djangosite/recipe_site/models/models.py
from django.db import models

# Create your models here.

djangosite/recipe_site/forms/user_registration.py
# from django.contrib.auth.forms import UserCreationForm
#
#
# class UserRegistrationForm(UserCreationForm):
#

djangosite/polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models.choice import Choice
from .models.question import Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects \
                   .filter(pub_date__lte=timezone.now()) \
                   .order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

djangosite/recipe_site/views/home.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "recipe_site/home.html"

djangosite/recipe_site/views/login_view.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

class LoginView(TemplateView):
    template_name = "recipe_site/login.html"

djangosite/recipe_site/views/recipes_index.py
from django.views.generic import TemplateView


class RecipeIndexView(TemplateView):
    template_name = "recipe_site/recipes.html"

djangosite/recipe_site/views/user_login.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect


class UserLoginView(LoginView):
    template_name = "recipe_site/login.html"

    def post(self, request, **kwargs):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            user = authenticate(request, username=form_data["username"], password=form_data["password"])

            if user is not None:
                login(request, user)
                return redirect("recipe_site:home")

        return render(request, self.template_name, {"form": form})

djangosite/recipe_site/views/user_login_view.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import path
from django.views.generic import TemplateView


# Create your views here.

class UserLoginView(LoginView):
    template_name = "recipe_site/login.html"
    next = "recipe_site/home.html"

    def post(self, request, **kwargs):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            user = authenticate(request, username=form_data["username"], password=form_data["password"])

            if user is not None:
                login(request, user)
                return render(request, self.next)

        return render(request, self.template_name, {"form": form})

djangosite/recipe_site/views/user_logout.py
from django.contrib.auth.views import LogoutView


class UserLogoutView(LogoutView):
    next_page = "recipe_site:login"

djangosite/recipe_site/views/user_logout_view.py
from django.contrib.auth.views import LogoutView


class UserLogoutView(LogoutView):
    next_page = "recipe_site:login"

djangosite/recipe_site/views/user_registration.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import FormView


class UserRegistrationView(FormView):
    template_name = "recipe_site/registration.html"
    form_class = UserCreationForm
    success_url = reverse_lazy('recipe_site:home')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)

        return HttpResponseRedirect(self.get_success_url())

djangosite/polls/templates/polls/detail.html
<form action="{% url "polls:vote" question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}
            <p>
                <strong>{{ error_message }}</strong>
            </p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio"
                   name="choice"
                   id="choice{{ forloop.counter }}"
                   value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <br/>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote"/>
</form>

djangosite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

djangosite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

djangosite/recipe_site/templates/recipe_site/base_home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <title>Reci.py</title>

        <link rel="stylesheet" href="{% static 'recipe_site/css/base_home.css' %}">

        {% block headers %}

        {% endblock %}
    </head>
    <body>

        <div class="nav-bar unselectable">
            <h1 class="logo">Reci.py</h1>
            <div class="nav-items nav-start">
                <div>
                    <a>Home</a>
                </div>
                <div>
                    <a href="{% url "recipe_site:recipes" %}">Recipes</a>
                </div>
            </div>

            <div class="nav-items nav-end">
                <div>
                    <a href="{% url "recipe_site:logout" %}">
                        Logout
                    </a>
                </div>
            </div>
        </div>

        {% block content %}

        {% endblock %}
    </body>
</html>

djangosite/recipe_site/templates/recipe_site/home.html
{% extends "recipe_site/base_home.html" %}

{% block content %}

    <h1>Home Page</h1>
    <h2>Welcome '{{ request.user }}'</h2>

{% endblock %}

djangosite/recipe_site/templates/recipe_site/landing_base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Reci.py Login</title>

        {% block headers %}

        {% endblock %}
        <link rel="stylesheet" href="{% static 'recipe_site/css/landing_base.css' %}">
    </head>
    <body>

        <div class="heading unselectable">
            <h1 class="logo">Reci.py</h1>
        </div>

        <div class="center-container">
            <div class="background unselectable">
                <img src="{% static "recipe_site/images/login-background.jpg" %}"
                     alt="Good looking food"/>
            </div>
            <div class="card-container">
                {% block card-content %}
                    <p>No card-content block defined</p>
                {% endblock %}
            </div>
        </div>

    </body>
</html>

djangosite/recipe_site/templates/recipe_site/login.html
{% extends "recipe_site/landing_base.html" %}
{% load static %}

{% block headers %}
    <link rel="stylesheet" href="{% static 'recipe_site/css/login.css' %}">
{% endblock %}

{% block card-content %}
    {% if not request.user.is_authenticated %}
        <h1>Login</h1>

        <form method="POST" action="{% url 'recipe_site:login' %}">
            <div class="login-input">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="login-input">
                {{ form.password.label_tag }}
                {{ form.password }}
            </div>
            {{ form.non_field_errors }}
            <div class="login-buttons">
                <input type="submit" value="Login">
                <input type="submit" value="Register" onclick="window.location='{% url 'recipe_site:register' %}';">
            </div>
            <input type="hidden" name="next" value="{{ next }}">
            {% csrf_token %}
        </form>
    {% else %}
        <h1>You are logged in as: <span class="logged-in-text">{{ request.user }}</span></h1>
        <div class="logout-btn">
            <input type="submit" value="Logout"
                   onclick="window.location='{% url 'recipe_site:logout' %}';"/>
        </div>
    {% endif %}
{% endblock %}

djangosite/recipe_site/templates/recipe_site/recipes.html
{% extends "recipe_site/base_home.html" %}

{% load static %}

{% block headers %}

{% endblock %}

{% block content %}

    <h1>Recipes Page</h1>

{% endblock %}

djangosite/recipe_site/templates/recipe_site/registration.html
{% extends "recipe_site/landing_base.html" %}
{% load static %}

{% block headers %}
    <link rel="stylesheet" href="{% static 'recipe_site/css/register.css' %}">
{% endblock %}


{% block card-content %}

    <h1>Register</h1>

    <form method="POST" action="{% url 'recipe_site:register' %}">
        {% for field in form %}
            <div class="form-group">
                {{ field.errors }}
                <div class="form-input">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
        <div>
            <input type="submit" value="Register">
        </div>
        {% csrf_token %}
    </form>

{% endblock %}